### ISSUE TITLE
Generation is quite slow

### ISSUE THREAD

**Issue by apuignav** [zfit/tfphasespace#1]
In my laptop:

```
[21:03]~/Arxiu/Fisica/LHCb/Projectes/zfit/tfphasespace[master](zfit-qokI31rn)$ python3 benchmark/bench_tfphasespace.py
2019-02-27 21:03:49.356016: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Elapsed time: 4126.743583000007 ms
[21:04]~/Arxiu/Fisica/LHCb/Projectes/zfit/tfphasespace[master](zfit-qokI31rn)$ time root -q benchmark/bench_tgenphasespace.cxx+

Processing benchmark/bench_tgenphasespace.cxx+...
(int) 0
root -l -q benchmark/bench_tgenphasespace.cxx+  0.24s user 0.12s system 101% cpu 0.344 total
```

I've factored out the import time of `tensorflow`, but still, not great. Also, generating large (1e9) samples is basically impossible, memory explodes (I understand that, though, `benchmark/bench_tgenphasespace.cx` doesn't save any info).

What can we do about it?

**Comment by mayou36** [comment]
So we should do a few things to have fair benchmarks:
- compile tf from source. This could most of all with the CPU instructions make a difference around 20%. Also choosing the right backend library (mkl, eigen) makes for me a difference around 20% (additionally)
- big difference: I added a first run without benchmarking. In this run, the graph is built. Subsequent runs are much faster (by order of 3-4x).
- While it is slower, it scales incredibly up to ~ 10 millions.
So for Eigen 100k -> 0.8s, 1 mio -> 2.4s, 10 mio -> 14s
For MKL lib: 100k -> 1.2s, 1 mio -> 3.0s, 10 mio -> 8s so producing 100 x as many events needs only 10x more time. This means there is quite some overhead, TF I guess. On my machine ROOT has ~ 2 secs for 10 mio (though ROOT is not multicore)

So yes, we are currently an order of magnitude slower (4 cores * 4 time ifference = 16). I'm trying to inspect the graph for bottlenecks

**Comment by apuignav** [comment]
This is nice! If we're a factor 10 slower is not a disaster, and I guess it's not likely that users will have an optimized installation anyway.

What annoys me is the graph building time, because even though of course it's artificial (graph building) in real life applications we'll see this problem. Also, if the user wants to generate again with a different number of events (for example doing integration) the graph will need to be rebuilt. It would be nice to be independent of the dimension, wouldn't it?

**Comment by mayou36** [comment]
I was wrong, sorry! And I like it: What I meant was _not_ the graph building time but the very first call to `run` (which really only happens once). I still created every time a new graph! So by building the graph just once, we get a factor of 2 speedup.
e.g. 10 mio -> 4 sec (compared to 2 sec in ROOT).

So for the n_events, I think we may can make that flexible: remember, we cannot change anything in the graph **except** of the value of n. So if we wrap it in an object and use caching (basically what we do all over the place in zfit, just think of loss -> create once the Tensor for loss, then cache it), we can get around the repeated graph building every time.

And we can also use variables for the limits.

**Comment by apuignav** [comment]
I was thinking the same thing. In principle, the `n_events` dimension is not needed to be known to build the graph, if we do the input preprocessing outside right? If we do that, then chunking also reruns the same graph so it should be faster.

**Comment by apuignav** [comment]
Is this closed by !2?

**Comment by mayou36** [comment]
yes

**Comment by apuignav** [comment]
Closing then.
